// Curated list of upcoming Blockbuster Movies & Web Series with official posters and trailers

export const UPCOMING_TITLES = [
  {
    id: 'up-1',
    imdbID: 'tt1757678',
    title: 'Avatar: Fire and Ash',
    releaseDate: 'December 19, 2027',
    year: '2027',
    type: 'movie',
    genre: 'Action, Adventure, Sci-Fi',
    director: 'James Cameron',
    cast: 'Sam Worthington, Zoe Saldaña, Sigourney Weaver, Oona Chaplin',
    poster: 'https://m.media-amazon.com/images/M/MV5BZDYxY2I1OGMtN2Y4MS00ZmU1LTgyNDAtODA0MzAyYjI0N2Y2XkEyXkFqcGc@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    plot: 'Jake Sully and Neytiri encounter a new, aggressive volcanic clan of Na\'vi known as the "Ash People" as the battle for Pandora escalates into uncharted territory.',
    trailerQuery: 'Avatar 3 Fire and Ash Official Trailer',
    trailerId: 'd9MyW72ELq0',
    status: 'In Post-Production'
  },
  {
    id: 'up-2',
    imdbID: 'tt4574334',
    title: 'Stranger Things (Season 5)',
    releaseDate: 'Summer 2027',
    year: '2027',
    type: 'series',
    genre: 'Drama, Fantasy, Horror',
    director: 'The Duffer Brothers',
    cast: 'Millie Bobby Brown, Finn Wolfhard, David Harbour, Winona Ryder',
    poster: 'https://m.media-amazon.com/images/M/MV5BMjEzMDAxOTUyMV5BMl5BanBnXkFtZTgwNzAxMzYzOTE@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80',
    plot: 'The ultimate final chapter. Hawkins is torn open by the Upside Down, and Eleven and the party must make their last stand against Vecna to save the world.',
    trailerQuery: 'Stranger Things Season 5 Official Teaser Trailer',
    trailerId: 'PssKpzB0Ah0',
    status: 'Final Season Coming Soon'
  },
  {
    id: 'up-3',
    imdbID: 'tt21357150',
    title: 'Avengers: Doomsday',
    releaseDate: 'December 18, 2026',
    year: '2026',
    type: 'movie',
    genre: 'Action, Adventure, Sci-Fi',
    director: 'Anthony Russo, Joe Russo',
    cast: 'Robert Downey Jr., Pedro Pascal, Chris Hemsworth, Vanessa Kirby',
    poster: 'https://m.media-amazon.com/images/M/MV5BMTdlMDgxNjAtNjkxOC00ZDYxLTg3MDEtZmIwZjIxOGMwYjVkXkEyXkFqcGc@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=80',
    plot: 'Heroes from three different worlds must unite when they are thrust together to confront a catastrophic danger that could destroy everything they know as Doctor Doom rises.',
    trailerQuery: 'Avengers Doomsday Marvel Trailer',
    trailerId: 'C9hU_urQJfg',
    status: 'In Production'
  },
  {
    id: 'up-latest-1',
    imdbID: 'tt27534307',
    title: 'Speak No Evil',
    releaseDate: 'September 13, 2026',
    year: '2026',
    type: 'movie',
    genre: 'Horror, Thriller',
    director: 'James Watkins',
    cast: 'James McAvoy, Mackenzie Davis, Scoot McNairy',
    poster: 'https://m.media-amazon.com/images/M/MV5BMWI2OWFjNjgtOTQ2Zi00MjlmLTg2MGYtNmE4MjMyZjIzMDA0XkEyXkFqcGc@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1600&q=80',
    plot: 'A family is invited to spend a weekend in an idyllic country house, unaware that their dream vacation will soon become a psychological nightmare.',
    trailerQuery: 'Speak No Evil Trailer',
    trailerId: 'TcMBFSGVi1c',
    status: 'In Theaters'
  },
  {
    id: 'up-latest-2',
    imdbID: 'tt8864596',
    title: 'Transformers One',
    releaseDate: 'September 20, 2026',
    year: '2026',
    type: 'movie',
    genre: 'Animation, Action, Adventure',
    director: 'Josh Cooley',
    cast: 'Chris Hemsworth, Brian Tyree Henry, Scarlett Johansson',
    poster: 'https://m.media-amazon.com/images/M/MV5BZWI1ZDY1YTQtMjRkNy00ZDZhLWE3OTItMTIwNzliY2Y1MTZhXkEyXkFqcGc@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1600&q=80',
    plot: 'The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.',
    trailerQuery: 'Transformers One Trailer',
    trailerId: 'mqqft2x_Aa4',
    status: 'In Theaters'
  },
  {
    id: 'up-4',
    imdbID: 'tt19850008',
    title: 'The Batman: Part II',
    releaseDate: 'October 1, 2027',
    year: '2027',
    type: 'movie',
    genre: 'Action, Crime, Drama',
    director: 'Matt Reeves',
    cast: 'Robert Pattinson, Colin Farrell, Andy Serkis, Jeffrey Wright',
    poster: 'https://m.media-amazon.com/images/M/MV5BMmU5NGJlMzAtMGNmOC00YjJjLTgyMzUtNjAyYmE4Njg5YWMyXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg',
    backdrop: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=1600&q=80',
    plot: 'Following the devastating flood of Gotham City, Batman delves deeper into the city\'s subterranean corruption as dangerous new rogues emerge to claim power.',
    trailerQuery: 'The Batman Part II Teaser Trailer',
    trailerId: 'vokDLPOEEhE',
    status: 'Filming Soon'
  },
  {
    id: 'up-5',
    imdbID: 'tt1190634',
    title: 'The Boys (Season 5)',
    releaseDate: 'Late 2027',
    year: '2027',
    type: 'series',
    genre: 'Action, Comedy, Drama',
    director: 'Eric Kripke',
    cast: 'Karl Urban, Antony Starr, Jack Quaid, Erin Moriarty',
    poster: 'https://m.media-amazon.com/images/M/MV5BZjU4OWNiYzQtMzc1NS00NjZlLTgyYTctZWY4ZmEzMTkxYjA4XkEyXkFqcGc@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1600&q=80',
    plot: 'The climactic final showdown. Homelander has seized total control of the United States government, leaving Butcher and the scattered Boys with no choice but all-out war.',
    trailerQuery: 'The Boys Season 5 Final Season Trailer',
    trailerId: '067YcwGkpkc',
    status: 'Final Season'
  },
  {
    id: 'up-6',
    imdbID: 'tt18224594',
    title: 'Blade Runner 2099',
    releaseDate: 'Fall 2027',
    year: '2027',
    type: 'series',
    genre: 'Drama, Mystery, Sci-Fi',
    director: 'Jonathan van Tulleken',
    cast: 'Michelle Yeoh, Hunter Schafer, Dimitri Abold',
    poster: 'https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX600.jpg',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1600&q=80',
    plot: 'Fifty years after Blade Runner 2049, a new mystery unfolds in Los Angeles examining what it truly means to be human in an era of advanced synthetic biology.',
    trailerQuery: 'Blade Runner 2099 Prime Video Teaser',
    trailerId: 'gCcx85zbxz4',
    status: 'Post-Production'
  }
];
